spring.application.name=ms-academico
server.port=8081


spring.datasource.url=jdbc:h2:file:./data/academicodb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Curso predeterminado (se crea al iniciar si no hay cursos en la BD)
app.curso-inicial.nivel=2 Medio
app.curso-inicial.letra=A
app.curso-inicial.anio=2026
app.curso-inicial.profesor-jefe-rut=12345678-9

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
